linux:
    image: rust:alpine
    script:
      - apk add build-base
      - export CARGO_HOME="$PWD/cargo"
      - cargo test
      - cargo build --release
    artifacts:
        expire_in: 2 weeks
        when: always
        paths:
            - target/release/dispatch-ng
    cache:
      key: cargo
      paths:
        - cargo
