[package]
name = "dispatch-ng"
version = "2.1.0"
edition = "2021"


[dependencies]
log = "0"
env_logger = "0"
futures = "0.3"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
